version: '3'

services:
  trust-service:
    image: nimbleplatform/trust-service:staging
    environment:
      KAFKA_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="token" password="2d4NjszlNV15bf1frbHgJ04pltCQoIQCrCemrFAqE38qThTW";
      KAFKA_BOOTSTRAP_SERVERS: kafka03-prod02.messagehub.services.eu-gb.bluemix.net:9093,kafka02-prod02.messagehub.services.eu-gb.bluemix.net:9093,kafka05-prod02.messagehub.services.eu-gb.bluemix.net:9093,kafka01-prod02.messagehub.services.eu-gb.bluemix.net:9093,kafka04-prod02.messagehub.services.eu-gb.bluemix.net:9093
      PORT: "9098"
      TRUST_DB_HOST: "trust-db"
      TRUST_DB_HOST_PORT: "5432"
      TRUST_DB_NAME: "trustdb"
      TRUST_DB_USERNAME: "admin"
      TRUST_DB_PASSWORD: "password"
    ports:
      - "9098:9098"

  trust-db:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: trustdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
    driver: local